# Generated by Django 5.1.1 on 2025-01-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_is_active_productline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
