# Generated by Django 5.1.1 on 2025-01-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_lines",
                to="product.product",
            ),
        ),
    ]
