# Generated by Django 5.1.1 on 2025-01-04 14:14

import product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_brand_is_active_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="order",
            field=product.fields.OrderField(blank=True, null=True),
        ),
    ]
