# Generated by Django 5.1.1 on 2025-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_productline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
