# Generated by Django 5.1.1 on 2025-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(default="text.jpg", upload_to=None),
        ),
    ]
