# Generated by Django 5.1.1 on 2025-01-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_productimage_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
